### ISSUE TITLE
Baikal compatibility issues with DSM 6.2.3

### ISSUE THREAD

**Issue by spoo333** [LaurentMarchelli/Baikal-DSM#4]
Hello,

Thank you for providing Baikal packages. 

When I install Baikal 0.4.6-001 on DSM 6.2.3-25426, I get the following error message in the Synology's Notifications section: "DSM cannot start up normally because it ran into a problem. Please contact the Synology support team for help." The moment I remove the Baikal package, everything works fine again and the message disappears. If I reboot the NAS before removing the Baikal packages, i cannot log into the Synology's web interface via the modified http and https ports - it sets itself to the defaults 5000 and 5001 ports.

Is Baikal not compatible with DSM 6.2.3 or is there a setting I can change to avoid the scenario above?

Thanks,
David

**Comment by LaurentMarchelli** [comment]
Hi spoo333,

The issue is a bit odd as it seems to appear on DS718+ but not on DS211, even if both have the same DSM version 6.2.3-2.
What is your Synology Model ?

It is even worse if you have redirected the http port to the https, as you do not have anymore access to the DSM, the only way is to uninstall the package from the command line, if you hopefully activated the ssh.
> synopkg uninstall baikal

I apologize for the inconvenience, I'm working on the bug fix.
I keep u informed,

Best regards,
Laurent Marchelli

**Comment by spoo333** [comment]
Hi Laurent,
many thanks for getting back to me on this issue. My synology is a DS418.
No need to apologise for anything. I appreciate you providing this package
free of charge. As far as I'm concerned, there is no need to rush as i
managed to get Synology's Carddav server going after all.
All the best to you,
David

**Comment by LaurentMarchelli** [comment]
Hi spoo333,

Thank you for your feed back, as the issue is now solved, it will benefit to all.

Best regards,
Laurent Marchelli

**Comment by spoo333** [comment]
Hi Laurent,
That's great news, thank you.
All the best,
David
